---
- name: Backup cisco ios configuration
  cisco.ios.ios_config:
    backup: true
    backup_options:
      dir_path: /tmp/test/
      filename: "{{ inventory_hostname }}.txt"
  register: config_output

