---
- name: Lanzar configuraciones ssh para los hosts
  hosts: localhost
  become: true
  roles:
    - role: 'roles/Configuraciones'

- name: Lanzar inicio de backup para los hosts seleccionados
  hosts: routers
  become: true
  roles:
    - role: 'roles/Backup'
    - role: 'roles/Removelines'
