- name: Lanzar inicio de backup para los hosts seleccionados
  hosts: routers
  become: true
  roles:
    - role: 'roles/Configuraciones'
    - role: 'roles/Qpoliticas'
    - role: 'roles/Backup'
    - role: 'roles/Removelines'
